### PR TITLE
Better graphics

### PR DESCRIPTION
**Pull request by demerzel3**
Because we all love shiny things

Help wanted: @maxcanna @daBarbe

### CODE REVIEW

**Comment by demerzel3** [comment]
@daBarbe how close is this to your vision?

schermata 2016-07-16 alle 00 11 51

**Comment by daBarbe** [comment]
It's really nice, but the image border should be thinner and the dots under the name should be a bit bigger.

Also, what about a black background?

**Comment by maxcanna** [comment]
I agree with @dabarbe. Regarding the background color I'd go with an optional query param. Something like dark theme.

**Comment by demerzel3** [comment]
Thinner colored border, doubled the size of dots.

schermata 2016-08-20 alle 20 04 32

It looks much better indeed, kudos @daBarbe.
I like it so I'm gonna merge it, we'll do multiple themes in another PR.

**Pull request merged**
